### ISSUE TITLE
SchemaNotFoundException when consuming Message

### ISSUE THREAD

**Issue by BeyerJC** [KonstantinCodes/avro-regy#1]
Hi !

I'm trying to consume a message from a topic. When i try, i get 
`
[FlixTech\SchemaRegistryApi\Exception\SchemaNotFoundException (40403)]  
  Schema 577074789 not found  
`
and theoretically i agree. There is no Schema in the registry with that ID but where does that value come from ? The correct schema id would be 42. 

Do you have an idea ? Maybe im doing something totally wrong. Can you maybe give an example how the Serializer for consuming messages could look like ?

**Comment by BeyerJC** [comment]
It looks like the message that is consumed with koco\kafkaMessenger does not include the bytes needed to extract the schemaId. 
The payload seems to just include the message in avro format.

Any idea ?

**Comment by KonstantinCodes** [comment]
@WhiteRabbitDE May I ask, how you solved the issue? Maybe I can improve the docs.

**Comment by BeyerJC** [comment]
@KonstantinCodes 
Hey ! Thanks for your reply. Unfortunatly, the Error was caused by me being stupid :-)

An explaination and a short discussion can be found here:

https://github.com/flix-tech/avro-serde-php/issues/61#issuecomment-937901218

PS: Thanks for the bundle!
